var Request = require("../models/request.js"),
    Hashids = require("hashids"),
    hashids = new Hashids("some");
/*
 * POST /requests
 */
exports.postrequests = function(req, res){
  // TODO: get autogenerated id
  console.log("post requests!");
  // TODO: Verify the request.
  var myTeamName = req.body["requestingTeamName"];
  var myLocation = req.body.location;
  var myTopic = req.body.topic;
  if(myTeamName === undefined || myLocation === undefined || myTopic === undefined) {
      res.send(1024);
  }
  
  var mssinceepoch = new Date().getTime();
  var newRequest = new Request({ 
    timestamp: mssinceepoch,
    requestingTeamName: myTeamName,
  	location: myLocation,
  	topic: myTopic});

    
  // generate and save shortid
  var shortid = hashids.encrypt(mssinceepoch);
  console.log("Post Request["+mssinceepoch+"] Short Id:"+[shortid]);
  newRequest.urlId = shortid;
  
  // Add it to database
  newRequest.save(function(err) {
    if(err) {
      console.log("Error on database save");
    }
  });

  // For Post, create and then 201
  res.setHeader('Location', '/requests/'+shortid);
  res.send(201);
};

/*
 * GET /requests
 */
exports.getrequests = function(req, res){
  console.log("get requests!");
  Request.find(function(err, requests) {
    console.log(requests);
    res.send(JSON.stringify(requests, null, 4));  
  });
};

/*
 * GET /requests/:id
 */
exports.getrequestsid = function(req, res){
  // Retrieve the original 
  var dbid = hashids.decrypt(req.params.id);
  Request.find({"urlId":req.params.id}, function(err, requests) {
    console.log(requests);
    if(requests.length) {
        console.log("WARNING: MULTIPLE WITH SAME ID");
    }
    res.send(JSON.stringify(requests[0], null, 4));  
  });
};

/*
 * PATCH /requests/:id
 */
exports.patchrequestsid = function(req, res){
    res.send("patch unimplemented");
};

/*
 * POST /logging
 */
exports.postlogging = function(req, res){
    res.send("logging unimplemented");
};

/*
 * POST /feedback
 */
exports.postfeedback = function(req, res){
    res.send("feedback unimplemented");
};



